[package]
name = "zed_vala"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-only"

[lib]
path = "src/vala.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.0.6"
