id = "vala"
name = "Vala"
version = "0.2.0"
schema_version = 1
authors = ["Lleyton Gray <lleyton@fyralabs.com>"]
description = "Vala support."
repository = "https://github.com/FyraLabs/zed-vala"

[grammars.vala]
repository = "https://github.com/hugmouse/tree-sitter-vala-fork"
commit = "b512130a32dd9c76183c265aae82f2624a05c700"

[language_servers.vls]
name = "Vala Language Server"
language = "Vala"
